[package]
name = "telegram-bot-template"
version = "0.1.0"
edition = "2018"

[dependencies]
tiny_http = "0.8"
frankenstein = "0.6"
eyre = "0.6.5"
pretty_env_logger = "0.4.0"
log = "0.4.14"
serde_json = "1.0.66"
config = "0.11.0"
serde = "1.0.129"
